Add UI Subscriber Detail screen
oscar-amezquita/MentorAppOA pull request #5
Opened 2017-07-12 22:04 UTC by oscar-amezquita

## Description

Adds the details of the selected user on the home screen and displays the list of repositories of the selected user.
- Add XML fragment resource.
- Add String resources.
- Add repositories adapter.
- Add repository model. 

## Evidence
<img src='https://user-images.githubusercontent.com/29235196/28141746-9f224a44-6723-11e7-80ff-1fdd4045cd91.png'>

2017-07-12 22:25 UTC, daniellemariani requested changes

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +public class UserDetailEntity {
Add javadoc

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    @Expose
Why expose?

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    public UserDetailEntity() {
Do you really need these constructor?

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    public void setLogin(String login) {
Remove setters

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepositoryModel.java
> +public class RepositoryModel {
Add Javadoc

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/adapter/UserRepositoriesAdapter.java
> +    private Context context;
Do you need this?

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +    <LinearLayout
Implement a RelativeLayout to re-create this distribution

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +    <RelativeLayout
This relative layout can be removed.

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="1dp"
Define dimension resource

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="1dp"
Same here

2017-07-12 22:25 UTC, daniellemariani commented on app/src/main/res/layout/list_repository_adapter.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
I would rename it to layout_repository_item or similar.

2017-07-13 16:46 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +public class UserDetailEntity {
Done, added.

2017-07-13 16:46 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    @Expose
Deleted.

2017-07-13 16:47 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    public UserDetailEntity() {
Constructor erased.

2017-07-13 16:47 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/model/UserDetailEntity.java
> +    public void setLogin(String login) {
done.

2017-07-13 16:48 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepositoryModel.java
> +public class RepositoryModel {
Done

2017-07-13 17:15 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +    <LinearLayout
Done.

2017-07-13 17:34 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +    <RelativeLayout
changed.

2017-07-13 20:23 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/adapter/UserRepositoriesAdapter.java
> +    private Context context;
Is used to get a zero constant  `context.getResources().getInteger(R.integer.zero_constant)`

2017-07-13 23:55 UTC, daniellemariani requested changes

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepositoryModel.java
> +public class RepositoryModel {
Isn't it a view model for Repository? A domain model is implemented mainly by Gson.
Also, you're using it in your RepositoryAdapter

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        View view = inflater.inflate(R.layout.fragment_user_details, container, false);
return the view directly since you're not using the view item

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +
Remove line

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +
Remove line

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
You can set this property in your _style/divider_ and also remove width and height from this element.
Also, margin properties can be moved to that style as well.

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
same here

2017-07-13 23:55 UTC, daniellemariani commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
same here

2017-07-14 14:50 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepositoryModel.java
> +public class RepositoryModel {
Yes, this class is located in the wrong package. Class moved.

2017-07-14 14:51 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        View view = inflater.inflate(R.layout.fragment_user_details, container, false);
Done.

2017-07-14 14:52 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +
Done.

2017-07-14 15:36 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
Done.

2017-07-14 15:36 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
Done

2017-07-14 15:36 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +
done.

2017-07-14 15:36 UTC, oscar-amezquita commented on app/src/main/res/layout/fragment_user_details.xml
> +        android:layout_height="@dimen/divider_height"
Done

2017-07-14 19:41 UTC, daniellemariani commented on app/src/main/res/values/strings.xml
> +    <string name="tv_detail_user_name">User Name: </string>
I think you are missing the variable so as to have the proper format

2017-07-14 20:03 UTC, oscar-amezquita commented on app/src/main/res/values/strings.xml
> +    <string name="tv_detail_user_name">User Name: </string>
it's true, Added.

2017-07-14 22:16 UTC, daniellemariani approved these changes
LG

2017-07-14 22:17 UTC, daniellemariani commented on app/src/main/res/values/strings.xml
> +    <string name="tv_detail_user_name">User Name: %s</string>
Minor question, this resource will show the Full Name or the username?

2017-07-14 22:24 UTC, oscar-amezquita commented on app/src/main/res/values/strings.xml
> +    <string name="tv_detail_user_name">User Name: %s</string>
show the "name"  field in the detail service e.g. `"name": "Ali Afshar" `

2017-07-14 22:24 UTC, daniellemariani commented on app/src/main/res/values/strings.xml
> +    <string name="tv_detail_user_name">User Name: %s</string>
Got it

2017-07-14 22:25 UTC, merged