Add MVP pattern in user details screen.
oscar-amezquita/MentorAppOA pull request #7
Opened 2017-07-21 17:02 UTC by oscar-amezquita

## Description
Use MVP pattern to make user details and download repo list. 
- Create Presenter to manage user details. 
- Create Presenter to manage List repositories.
- Create interactor to get data from GitHub services.
- Create Presentation view to manage data exchange.
- reorder packages to adjust features and general classes.

## Evidence
<img width=270 src='https://user-images.githubusercontent.com/29235196/28473979-62b4b53e-6e0c-11e7-91f1-6f4d33e1a36a.gif'>

2017-07-21 17:40 UTC, daniellemariani requested changes

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        public ViewHolder(View itemView, final Context context) {
You do not need this context parameter, since you can get it from itemView, which is a View.

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +                    UserDetailsFragment detailsFragment = UserDetailsFragment.getInstance();
Avoid doing this. Click events in adapters MUST be managed in the Activity or Fragment, the adapter should never manage the navigation of the app.

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/interactor/FetchUserDetailsInteractor.java
> +
What happens if it fails? The presenter is never notified of this escenario, the same for the UI and User.

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> + * Created by oscar.amezquita on 17/07/2017.
Javadoc

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> +    public Boolean get_private() {
Respect java conventions. Avoid "_" in methods name. The use of "_" in methods names is for unit tests mainly.

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/model/DetailsModel.java
> +public class DetailsModel {
UserDetailsModel*
Try to define self-descriptive names always

2017-07-21 17:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +
Remove extra line

2017-07-21 18:52 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        public ViewHolder(View itemView, final Context context) {
Done

2017-07-21 18:52 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +                    UserDetailsFragment detailsFragment = UserDetailsFragment.getInstance();
Done, listener added.

2017-07-21 18:53 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/interactor/FetchUserDetailsInteractor.java
> +
It's true, code added.

2017-07-21 18:56 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> + * Created by oscar.amezquita on 17/07/2017.
Done. Added.

2017-07-21 18:58 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> +    public Boolean get_private() {
Ok, done.

2017-07-21 19:00 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/model/DetailsModel.java
> +public class DetailsModel {
Done.

2017-07-21 23:03 UTC, daniellemariani requested changes

2017-07-21 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/interactor/FetchUserListInteractor.java
> +import com.globant.example.mentorapp.data.remote.EventApiResponseEntity;
Wasn't this going to be a UserListResponseEvent?

2017-07-21 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        ViewHolder(View itemView, final Context context) {
You do not need the Context parameter

2017-07-21 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/fragment/ListUsersViewFragment.java
> +    public void onUserSelected(String userId) {
Excellent!

2017-07-21 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/fragment/ListUsersViewFragment.java
> +        bundle.putString("userId", userId);
Define constant

2017-07-21 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseRecyclerViewAdapter.java
> +public class BaseRecyclerViewAdapter {
Do you really need to define this class, do you expect to implement onUserClick in many places?

2017-07-24 15:02 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/interactor/FetchUserListInteractor.java
> +import com.globant.example.mentorapp.data.remote.EventApiResponseEntity;
It's, UserListResponseEntity class created.

2017-07-24 16:11 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        ViewHolder(View itemView, final Context context) {
True, context erased.

2017-07-24 16:23 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/fragment/ListUsersViewFragment.java
> +        bundle.putString("userId", userId);
done.

2017-07-24 16:30 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseRecyclerViewAdapter.java
> +public class BaseRecyclerViewAdapter {
I thought to use it in the repository list when the user selects a repository, open the repository website, but this functionality will be in another PR.

2017-08-01 00:30 UTC, daniellemariani requested changes

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/domain/response/UserListResponseEntity.java
> + * Created by oscar.amezquita on 24/07/2017.
Add javadoc

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +                    listener.onUserSelected(userNameTextView.getText().toString());
You can set the User instance or the Username to this ViewHolder so you avoid calling the View getter

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseRecyclerViewAdapter.java
> +    public interface onUserClick {
Do you expect to have user clicks all your adapters? This listener can be moved to the fragment that implements the adapter

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/interactor/FetchUserDetailsInteractor.java
> +    public FetchUserDetailsInteractor(APIService apiService, Bus bus) {
You can create a BaseInteractor for this block to  avoid boilerplate code

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> +public class ListReposEntity {
This is not a list, it represents a single Repo

2017-08-01 00:30 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/model/UserDetailsModel.java
> +    private String imageUrl;
final?

2017-08-01 16:02 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/domain/response/UserListResponseEntity.java
> + * Created by oscar.amezquita on 24/07/2017.
Done.

2017-08-01 16:41 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +                    listener.onUserSelected(userNameTextView.getText().toString());
Done.

2017-08-01 16:59 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseRecyclerViewAdapter.java
> +    public interface onUserClick {
Done.

2017-08-01 17:30 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/interactor/FetchUserDetailsInteractor.java
> +    public FetchUserDetailsInteractor(APIService apiService, Bus bus) {
Done

2017-08-01 19:03 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/ListReposEntity.java
> +public class ListReposEntity {
Done

2017-08-01 21:00 UTC, daniellemariani requested changes

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    public ListUsersAdapter(List<ModelUserEntity> users) {
You should keep the clickListener as parameter

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private ListUsersViewFragment fragmentListener;
Keep a descriptive name like OnUserClickListener. I just pointed to move it to the fragment.

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        holder.userNameTextView.setText(holder.user.getName());
This is a bit confusing. You can have a setUser method in your view holder and set the data in the view components there.

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseInteractor.java
> +public class BaseInteractor {
👍

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseInteractor.java
> +
Remove extra line

2017-08-01 21:00 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseInteractor.java
> +    protected APIService apiService;
You may also declare them as final.

2017-08-01 21:38 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private ListUsersViewFragment fragmentListener;
Ok, done.

2017-08-01 21:55 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseInteractor.java
> +
Done.

2017-08-01 21:55 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseInteractor.java
> +    protected APIService apiService;
Done.

2017-08-01 21:55 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        holder.userNameTextView.setText(holder.user.getName());
It's true. Done.

2017-08-02 15:08 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    public ListUsersAdapter(List<ModelUserEntity> users) {
Done.

2017-08-02 23:03 UTC, daniellemariani requested changes

2017-08-02 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private ListUsersViewFragment.OnUserClickListener onUserClickListener;
Excuse me if I confused you regarding this. My point is OnUserClickListener should be an interface define in this class and implemented by your Fragment. And inside your fragment you just need to pass `this` as parameter in the adapter constructor.

2017-08-02 23:03 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/fragment/ListUsersViewFragment.java
> +            listUsersAdapter = new ListUsersAdapter(model.getUsers().getValue(), new OnUserClickListener());
Define just one new instance of the ListUserAdapter, if the data must be refreshed you can pass it through a setter method and notify the adapter.

2017-08-03 15:19 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private ListUsersViewFragment.OnUserClickListener onUserClickListener;
It's true, I made an interface in the adapter and implemented this interface in the fragment.

2017-08-04 01:40 UTC, daniellemariani requested changes

2017-08-04 01:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private selectionListener onUserClickListener;
The first letter of Classes/Interfaces must be in Capital (Letter case)

2017-08-04 01:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepoEntity.java
> +    private Integer id;
Why Integer?

2017-08-04 01:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepoEntity.java
> +    private Boolean _private;
Why Boolean? also remove the **_**

2017-08-04 01:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/model/UserDetailsModel.java
> +        public Builder() {
Not needed

2017-08-04 01:40 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +    private void usersErrorHttp() {
You can have a single method that receive the message as parameter

2017-08-04 14:06 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +    private selectionListener onUserClickListener;
It´s true. Done.

2017-08-04 14:09 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepoEntity.java
> +    private Integer id;
It's not necessary, changed.

2017-08-04 14:20 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/domain/model/RepoEntity.java
> +    private Boolean _private;
Ok, changed to 'boolean' and name changed to 'private_'

2017-08-04 14:31 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/model/UserDetailsModel.java
> +        public Builder() {
True, deleted.

2017-08-04 15:05 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +    private void usersErrorHttp() {
Done, modified.

2017-08-08 20:34 UTC, daniellemariani requested changes

2017-08-08 20:34 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +    private void usersRepositoryListReady(RecyclerView recyclerView, RecyclerView.Adapter adapter) {
If these attributes are part of the class, why are you passing them as parameters?

2017-08-08 20:34 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
You're creating this manager every time you call this method. You can initialize these attributes when you get the recycler view instance

2017-08-08 20:34 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        void onUserSelected(String id);
Actually, you're not passing an id. Let's use the proper name for this variable: username or login (as it's called in GitHub)

2017-08-08 20:34 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseFragment.java
> +        parent.simpleSnackBarMessage(message);
Can it be null?

Also, you can initialize these attributes in this class if the logic applies for all the child classes

2017-08-08 20:39 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +    private void usersRepositoryListReady(RecyclerView recyclerView, RecyclerView.Adapter adapter) {
It's true, is not necessary.  Deleted.

2017-08-08 20:40 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
Done.

2017-08-08 20:49 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/home/presentation/view/adapter/ListUsersAdapter.java
> +        void onUserSelected(String id);
Done.

2017-08-08 21:50 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/mvp/base/BaseFragment.java
> +        parent.simpleSnackBarMessage(message);
Done.

2017-08-10 21:46 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        listReposRecyclerView.addItemDecoration(
You can execute the blocked between lines 160 to 164 just once after initializing listReposRecyclerView object.

2017-08-11 16:11 UTC, oscar-amezquita commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        listReposRecyclerView.addItemDecoration(
Done.

2017-08-17 23:14 UTC, daniellemariani commented on app/src/main/java/com/globant/example/mentorapp/subscriberDetails/presentation/view/fragment/UserDetailsFragment.java
> +        listReposRecyclerView.setLayoutManager(layoutManager);
setLayoutManager and setAdapter can be moved to onCreateView

2017-08-22 20:48 UTC, merged